# Generated by Django 4.2.6 on 2023-10-24 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("sent_on", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
